lovedale/accounts/urls.py
from accounts import views
from django.urls import path

app_name="accounts"

urlpatterns = [
    
    path('register/', views.user_register,name="register"),
    path('login/', views.user_login,name="login"),
    path('profile_update/', views.profile_update,name="profile_update"),
    path('accounts/activate/<str:uidb64>/<str:token>/', views.activate, name='activate'),
    path('logout/',views.user_logout, name='logout'),
    
    
]

lovedale/lovedale/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lovers.urls')),
    path('', include('accounts.urls')),
    # path('dj-admin/', include('customadmin.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

lovedale/lovers/urls.py
from lovers import views
from django.urls import path

app_name="lovers"

urlpatterns = [
    path('', views.index,name="index"),
    path('profile/', views.profile,name="profile"),
    # path('propose/', views.user_propose,name="propose"),
    path('upload/', views.identity, name='upload_file'),
    path('propose/', views.propose, name='propose'),
    path('view/<str:file_name>/', views.view_encrypted_image, name='view_encrypted_image'),
    path('accepte_proposal/<int:prop_id>/', views.accepte_proposal, name='accepte_proposal'),
    path('reject_proposal/<int:prop_id>/', views.reject_proposal, name='reject_proposal'),
    path('verify_paid/', views.pay_verify, name='verify_paid'),
    path('pdf/', views.pdf, name='pdf'),
    path('relationship_agreement_to_pdf/', views.relationship_agreement_to_pdf, name='relationship_agreement_to_pdf'),
    path('user_verify/', views.user_verify, name='user_verify'),

    
    
    
]

lovedale/lovers/models.py
# Create your models here.
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin, Group, Permission
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

class CustomUserManager(BaseUserManager):
    def create_user(self, username, phone_number, password=None, **extra_fields):
        if not username:
            raise ValueError('The Username must be set')
        if not phone_number:
            raise ValueError('The Phone Number must be set')

        user = self.model(
            username=username,
            phone_number=phone_number,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, phone_number, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(username, phone_number, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    username = models.CharField(max_length=150, unique=True)
    age = models.IntegerField(blank=True, null=True)
    phone_number = models.CharField(max_length=15, unique=True)
    email = models.EmailField(unique=True)
    status = models.CharField(max_length=50,blank=True, null=True)
    verified = models.BooleanField(default=False)
    gender = models.CharField(max_length=10,blank=True,null=True)
    registered_date = models.DateTimeField(default=timezone.now)
    last_login = models.DateTimeField(null=True, blank=True)
    terms_and_conditions = models.BooleanField(default=False,blank=True, null=True)
    verify_paid=models.BooleanField(default=False)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    profile_picture = models.ImageField(upload_to='profile_pictures', blank=True, null=True)
    cover_picture = models.ImageField(upload_to='cover_pictures', blank=True, null=True)
    bio = models.TextField(blank=True)
    work = models.CharField(max_length=255, blank=True)
    education = models.CharField(max_length=255, blank=True)
    place = models.CharField(max_length=255, blank=True)
    

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['name', 'phone_number', 'email']

    objects = CustomUserManager()

    def __str__(self):
        return self.username

    class Meta:
       permissions = [
            ('can_view_customuser', 'Can view custom users'),
            ('can_change_customuser', 'Can change custom users'),
            ('can_delete_customuser', 'Can delete custom users'),
        ]

    user_permissions = models.ManyToManyField(
        Permission,
        verbose_name=_('user permissions'),
        blank=True,
        related_name='customuser_permissions',
        related_query_name='customuser_permission',
    )

    groups = models.ManyToManyField(
        Group,
        verbose_name=_('groups'),
        blank=True,
        related_name='customuser_groups',
        related_query_name='customuser_group',
        help_text=_(
            'The groups this user belongs to. A user will get all permissions '
            'granted to each of their groups.'
        ),
    )


class UserPropose(models.Model):
    party_a=models.CharField(max_length=150)
    party_b=models.CharField(max_length=150)
    propose_id=models.CharField(max_length=150, unique=True)
    accepte=models.BooleanField(null=True)
    propose_date=models.DateTimeField(default=timezone.now)
    sing_1=models.ImageField(upload_to='sing_1', blank=True, null=True)
    sing_2=models.ImageField(upload_to='sing_2', blank=True, null=True)
    re_props=models.IntegerField(blank=True, null=True,default=0)
    
    

lovedale/templates/account_activation_link.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email Template</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        .container {
            align-items: center;
            
            margin: 0 auto;
            padding: 20px;
            
        }
        .card {
            margin-left: 10%;
            margin-right: 10%;
            border: 1px solid #ccc;
            border-radius: 5px;
            padding: 20px;
            margin-top: 20px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            
        }
        .btn {
            background-color: #007bff;
            color: #fff;
            text-decoration: none;
            padding: 10px 20px;
            border-radius: 5px;
            display: inline-block;
        }
    </style>
</head>
<body>

    <div class="container">
        <div class="card">
            <div class="card-body">

            
            <p>Dear user {{uname}},</p>

            <p>Thank you for registering with us. To complete your registration and activate your account, please click the button below:</p>

            <a class="btn" href="http://127.0.0.1:8000/accounts/activate/{{uid}}/{{ttoken}}">Activate</a>

            <div style="margin-top: 20px;">
                <p>If the button above doesn't work, you can also activate your account by copying and pasting the following link into your browser:
                <a href="http://127.0.0.1:8000/accounts/activate/{{uid}}/{{ttoken}}">link</a></p>
            </div>
        </div>
        
        </div>

        <div style="margin-top: 20px;">
            <p>Please review the information provided and take the necessary steps.</p>
            <p>Best regards,<br>Your Company Name</p>
        </div><span>note this is not a official site</span>
    </div>

</body>
</html>

lovedale/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <!-- Font Awesome -->
<link
href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
rel="stylesheet"
/>
<!-- Google Fonts --> 
<!-- <link
href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
rel="stylesheet"
/> -->
<!-- MDB -->
<!-- <link
href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.1.0/mdb.min.css"
rel="stylesheet"
/>  -->
    <title>Document</title>

    <style>
      html,body{
  margin:0px;
  height:100%;
}
.bg_heart{
  position:relative;
  top:0;
  left:0;
  width:100%;
  height:100%;
 overflow:hidden;
  background-image:url("https://i.pinimg.com/originals/51/d8/37/51d8374126446d495348b6032202126f.jpg");
  background-size:100% 100%;
  z-index:-1;
}

.container-fluid{
  position:absolute;
  top:0;
  
  height:100%;
  width:100%;
  text-align:center;
  color:white;
  font-family:cursive;
}


.heart{
  position:absolute;
  top:-50%;
  transform:rotate(-45deg);
  -webkit-transform:rotate(-45deg);
  -moz-transform:rotate(-45deg);
  -m-transform:rotate(-45deg);
}
.heart:before{
  position:absolute;
  top:-50%;
  left:0;
  display:block;
  content:"";
  width:100%;
  height:100%;
  background:inherit;
  border-radius:100%;
}
.heart:after{
  position:absolute;
  top:0;
  right:-50%;
  display:block;
  content:"";
  width:100%;
  height:100%;
  background:inherit;
  border-radius:100%;
}

@keyframes love {
  0%{top:110%}
}
@-webkit-keyframes love {
  0%{top:110%}
}
@-moz-keyframes love {
  0%{top:110%}
}
@-ms-keyframes love {
  0%{top:110%}
}


.navbar-light .navbar-nav .nav-link {
  color: #000;
}

/* for notification */
@keyframes fadeOut {
        from { opacity: 3; }
        to { opacity: -1; }
        }

    </style>
</head>
<body>

   <!-- Navbar -->
<!-- <nav class="navbar navbar-expand-lg fixed-top bg-light navbar-light">
  <div class="container">
    <a class="navbar-brand" href="#"
      ><img
        id="MDB-logo"
        src="https://mdbcdn.b-cdn.net/wp-content/uploads/2018/06/logo-mdb-jquery-small.png"
        alt="MDB Logo"
        draggable="false"
        height="30"
    /></a>
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarSupportedContent1"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent1">
      <ul class="navbar-nav ms-auto align-items-center">
        <li class="nav-item">
          <a class="nav-link mx-2" href="#!"><i class="fas fa-plus-circle pe-2"></i>Post</a>
        </li>
        <li class="nav-item">
          <a class="nav-link mx-2" href="#!"><i class="fas fa-bell pe-2"></i>Alerts</a>
        </li>
        <li class="nav-item">
          <a class="nav-link mx-2" href="#!"><i class="fas fa-heart pe-2"></i>Trips</a>
        </li>
        <li class="nav-item ms-3">
          <a class="btn btn-black btn-rounded" href="#!">Sign in</a>
        </li>
      </ul>
    </div>
  </div>
</nav> -->

 


  <div class="bg_heart">
    
  </div>
  
  <div class="container-fluid">
    
    
    
   
  <div class="mt-5" style="height: 450px;">
    <h2 id="text1"></h2>
  </div>  
  
  
  
  <div>
    <div>
      <div>
        <a class="btn btn-success" href="{% url 'accounts:register' %}">Register</a>
        <a class="btn btn-primary" href="{% url 'accounts:login' %}">Login</a>
        
      </div>
    </div>
  </div>
</div>
  
  
    
    


    {% for msg in messages %}

<div id="message" style="position: fixed;bottom: 50px;right: 0;width: auto;">
  <div class="alert  alert-dismissible " style="margin: 0 auto;background-color: #ffffff;border-color: #00000087;border-width: 2px;box-shadow: 0 0 15px rgba(0, 0, 0, 0.8);">
    <i class="fa-solid fa-circle-check" style="color: #05eb09;"></i>
    <span style="color: #000000;font-size: 19px;padding-left: 10px;">{{ msg }}</span> 
  </div>
</div>
{% endfor %}


<script>
    document.addEventListener("DOMContentLoaded", function () {
        var alertBox = document.querySelector("#message");
  
        setTimeout(function () {
            alertBox.style.animation = "fadeOut 1.0s ease-out";
            setTimeout(function () {
                alertBox.style.display = "none";
            }, 500);
        }, 7000);
    });
  </script>

  <script>
    
var love = setInterval(function(){
  var r_num = Math.floor(Math.random() * 40) + 1;
  var r_size = Math.floor(Math.random() * 65) + 10;
  var r_left = Math.floor(Math.random() * 100) + 1;
  var r_bg = Math.floor(Math.random() * 25) + 100;
  var r_time = Math.floor(Math.random() * 5) + 5;
  $('.bg_heart').append("<div class='heart' style='width:"+r_size+"px;height:"+r_size+"px;left:"+r_left+"%;background:rgba(255,"+(r_bg-25)+","+r_bg+",1);-webkit-animation:love "+r_time+"s ease;-moz-animation:love "+r_time+"s ease;-ms-animation:love "+r_time+"s ease;animation:love "+r_time+"s ease'></div>");
  
  $('.bg_heart').append("<div class='heart' style='width:"+(r_size-10)+"px;height:"+(r_size-10)+"px;left:"+(r_left+r_num)+"%;background:rgba(255,"+(r_bg-25)+","+(r_bg+25)+",1);-webkit-animation:love "+(r_time+5)+"s ease;-moz-animation:love "+(r_time+5)+"s ease;-ms-animation:love "+(r_time+5)+"s ease;animation:love "+(r_time+5)+"s ease'></div>");
  
  
},500);

var i = 0;
var txt1 = "Hi SweetHeart.....!  <<               Now I wan't to say something special to you. <<<                So , Please read everything carefully...!                                                                           > When I saw you for the first time < You seems something Special to me.  <<                  As the days goes < you get closer to me....! <<                           I don't know the reason why your thoughts always resonates inside my mind...!                                                     > Everything about you is always intresting for me...!                     << I am somewhat nervous Because I haven't said these words to anyone and I won't say to anyone in future...!                                                     > I Love my Parents so much than anything else in this world....!                    << Now You are the only person  whom I love equally with my parents....!                                                             >I Love U <SweetHeart.....! |                  <<<< Give me One chance to Prove my Love ...!";
var speed = 50;
typeWriter();
function typeWriter() {
  if (i < txt1.length) {        
     if(txt1.charAt(i)=='<')
      document.getElementById("text1").innerHTML += '</br>'
    else if(txt1.charAt(i)=='>')
      document.getElementById("text1").innerHTML = ''
    else if(txt1.charAt(i)=='|')
      {
        $(".bg_heart").css("background-image","url('https://i.pinimg.com/originals/51/d8/37/51d8374126446d495348b6032202126f.jpg')");

      }
    else
      document.getElementById("text1").innerHTML += txt1.charAt(i);
    i++;
    setTimeout(typeWriter, speed);
  }
}
  </script>
    
</body>
</html>

lovedale/templates/user_verify.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email Template</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        .container {
            align-items: center;
            
            margin: 0 auto;
            padding: 20px;
            
        }
        .card {
            margin-left: 10%;
            margin-right: 10%;
            border: 1px solid #ccc;
            border-radius: 5px;
            padding: 20px;
            margin-top: 20px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            
        }
        .btn {
            background-color: #007bff;
            color: #fff;
            text-decoration: none;
            padding: 10px 20px;
            border-radius: 5px;
            display: inline-block;
        }
    </style>
</head>
<body>

    <div class="container">
        <div class="card">
            <div class="card-body">

            
            <p>user {{uname}},</p>

            <p>The user requested to verify his/her account bellow are the details</p>

            <li>
                <ul>user id : {{u_id}}</ul>
                <ul>username : {{u_username}}</ul>
                <ul>age : {{u_age}}</ul>
                <ul>gender : {{u_gender}}</ul>
                <ul>phone number : {{u_phone_number}}</ul>
                <ul>email id : {{u_email}}</ul>
                
            </li>



            
        </div>
        
        </div>

        <div style="margin-top: 20px;">
            <p>Please review the information provided and take the necessary steps.</p>
            <p>Best regards,<br>Your Company Name</p>
        </div><span>note this is not a official site</span>
    </div>

</body>
</html>

lovedale/templates/userlogin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <!-- Font Awesome -->
<link
href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
rel="stylesheet"
/>
<!-- Google Fonts --> 
<!-- <link
href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
rel="stylesheet"
/> -->
<!-- MDB -->
<!-- <link
href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.1.0/mdb.min.css"
rel="stylesheet"
/>  -->
    <title>Document</title>

    <style>
      html,body{
  margin:0px;
  height:100%;
}
.bg_heart{
  position:relative;
  top:0;
  left:0;
  width:100%;
  height:100%;
 overflow:hidden;
  background-image:url("{% static 'assets/img/bg-3.jpg' %}");
  background-size:100% 100%;
  z-index:-1;
}

.container-fluid{
  position:absolute;
  top:0;
  
  height:100%;
  width:100%;
  text-align:center;
  color:white;
  font-family:cursive;
}


.heart{
  position:absolute;
  top:-50%;
  transform:rotate(-45deg);
  -webkit-transform:rotate(-45deg);
  -moz-transform:rotate(-45deg);
  -m-transform:rotate(-45deg);
}
.heart:before{
  position:absolute;
  top:-50%;
  left:0;
  display:block;
  content:"";
  width:100%;
  height:100%;
  background:inherit;
  border-radius:100%;
}
.heart:after{
  position:absolute;
  top:0;
  right:-50%;
  display:block;
  content:"";
  width:100%;
  height:100%;
  background:inherit;
  border-radius:100%;
}

@keyframes love {
  0%{top:110%}
}
@-webkit-keyframes love {
  0%{top:110%}
}
@-moz-keyframes love {
  0%{top:110%}
}
@-ms-keyframes love {
  0%{top:110%}
}


.navbar-light .navbar-nav .nav-link {
  color: #000;
}

/* for notification */
@keyframes fadeOut {
        from { opacity: 3; }
        to { opacity: -1; }
        }

    </style>
</head>
<body>

   <!-- Navbar -->
<!-- <nav class="navbar navbar-expand-lg fixed-top bg-light navbar-light">
  <div class="container">
    <a class="navbar-brand" href="#"
      ><img
        id="MDB-logo"
        src="https://mdbcdn.b-cdn.net/wp-content/uploads/2018/06/logo-mdb-jquery-small.png"
        alt="MDB Logo"
        draggable="false"
        height="30"
    /></a>
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarSupportedContent1"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent1">
      <ul class="navbar-nav ms-auto align-items-center">
        <li class="nav-item">
          <a class="nav-link mx-2" href="#!"><i class="fas fa-plus-circle pe-2"></i>Post</a>
        </li>
        <li class="nav-item">
          <a class="nav-link mx-2" href="#!"><i class="fas fa-bell pe-2"></i>Alerts</a>
        </li>
        <li class="nav-item">
          <a class="nav-link mx-2" href="#!"><i class="fas fa-heart pe-2"></i>Trips</a>
        </li>
        <li class="nav-item ms-3">
          <a class="btn btn-black btn-rounded" href="#!">Sign in</a>
        </li>
      </ul>
    </div>
  </div>
</nav> -->

 


  <div class="bg_heart">
    
  </div>
  
  <div class="container-fluid">
    {% for msg in messages %}

    <div id="message" style="position: fixed;bottom: 50px;right: 0;width: auto;">
      <div class="alert  alert-dismissible " style="margin: 0 auto;background-color: #ffffff;border-color: #00000087;border-width: 2px;box-shadow: 0 0 15px rgba(0, 0, 0, 0.8);">
        <!-- <i class="fa-solid fa-circle-xmark" style="color: #eb0505;"></i> -->
        <span style="color: #000000;font-size: 19px;padding-left: 10px;">{{ msg }}</span> 
      </div>
    </div>
    {% endfor %}
    <div class="container mt-4">
      <div class="row">
        <div class="col-1">
          <a href="/"><i class="fa-solid fa-circle-arrow-left" style="font-size: 30px;"></i></a>
        </div>
        
      </div>
      
    </div>
    
    <div >
      
      </div>
      
    
    
   
  <!-- <div class="mt-5" style="opacity: 0.8;background-color: #05eb09;">
    <div class="card" style="color: #000;">
        <div class="card-body" >

            <form method="post" action="" enctype="multipart/form-data">
                {% csrf_token %}
                <label for="id_name">Name:</label>
                <input type="text" id="id_name" name="name" required><br>
            
                <label for="id_username">Username:</label>
                <input type="text" id="id_username" name="username" required><br>
            
                <label for="id_age">Age:</label>
                <input type="number" id="id_age" name="age" required><br>
            
                <label for="id_phone_number">Phone Number:</label>
                <input type="text" id="id_phone_number" name="phone_number" required><br>
            
                <label for="id_email">Email:</label>
                <input type="email" id="id_email" name="email" required><br>
            
                <label for="id_password">Password:</label>
                <input type="password" id="id_password" name="password" required><br>
            
                <input type="checkbox" id="id_terms_and_conditions" value=True name="terms_and_conditions" required>
                <label for="id_terms_and_conditions">I agree to the terms and conditions</label><br>
            
                <button type="submit">Register</button>
            </form>

        </div>
    </div>
  </div>   -->
  
  <div class="container">
    
    <section class="gradient-custom mb-5" >
      <div class="container  ">
        <div class="row justify-content-center align-items-center ">
          <div class="col-md-4">
            <div class="card shadow-2-strong card-registration" style="border-radius: 15px;opacity: 0.9;">
              <div class="card-body p-4 p-md-5">
                <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">Login</h3>
                
                <form method="post" action="{% url 'accounts:login' %}" >
                  {% csrf_token %}
    
                  <div class="row">
                    
                    <div class="col-md-12 mb-1">
    
                      <div class="form-outline">
                        <input type="text" id="username" name="username_or_phone" class="form-control form-control-sm" />
                        <label class="form-label" for="username">username</label>
                      </div>

                      
                        <div class="form-outline">
                          <input type="password" id="password" name="password" class="form-control form-control-sm" />
                          <label class="form-label" for="password">Password</label>
                          <i class="fa fa-eye-slash" id="togglePassword"></i>
                        </div>
                      
    
                    </div>
                  </div>
                  <div class="   pt-2">
                    <button class="btn btn-primary" type="submit">login</button>
                  </div>
    
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
</div>
<script>
    const togglePassword = document.querySelector("#togglePassword");
    const password = document.querySelector("#password");

    togglePassword.addEventListener("click", function () {
        // toggle the type attribute
        const type = password.getAttribute("type") === "password" ? "text" : "password";
        password.setAttribute("type", type);
        
        // toggle the icon
        this.classList.toggle('fa-eye-slash');
        this.classList.toggle('fa-eye');
    });

    // prevent form submit
    
</script>
  
  
  
 
  
  
    
    


   
</div>


<script>
    document.addEventListener("DOMContentLoaded", function () {
        var alertBox = document.querySelector("#message");
  
        setTimeout(function () {
            alertBox.style.animation = "fadeOut 1.0s ease-out";
            setTimeout(function () {
                alertBox.style.display = "none";
            }, 500);
        }, 7000);
    });
  </script>

  <script>
    
var love = setInterval(function(){
  var r_num = Math.floor(Math.random() * 40) + 1;
  var r_size = Math.floor(Math.random() * 65) + 10;
  var r_left = Math.floor(Math.random() * 100) + 1;
  var r_bg = Math.floor(Math.random() * 25) + 100;
  var r_time = Math.floor(Math.random() * 5) + 5;
  $('.bg_heart').append("<div class='heart' style='width:"+r_size+"px;height:"+r_size+"px;left:"+r_left+"%;background:rgba(255,"+(r_bg-25)+","+r_bg+",1);-webkit-animation:love "+r_time+"s ease;-moz-animation:love "+r_time+"s ease;-ms-animation:love "+r_time+"s ease;animation:love "+r_time+"s ease'></div>");
  
  $('.bg_heart').append("<div class='heart' style='width:"+(r_size-10)+"px;height:"+(r_size-10)+"px;left:"+(r_left+r_num)+"%;background:rgba(255,"+(r_bg-25)+","+(r_bg+25)+",1);-webkit-animation:love "+(r_time+5)+"s ease;-moz-animation:love "+(r_time+5)+"s ease;-ms-animation:love "+(r_time+5)+"s ease;animation:love "+(r_time+5)+"s ease'></div>");
  
  
},500);

var i = 0;
var txt1 = "Hi SweetHeart.....!  <<               Now I wan't to say something special to you. <<<                So , Please read everything carefully...!                                                                           > When I saw you for the first time < You seems something Special to me.  <<                  As the days goes < you get closer to me....! <<                           I don't know the reason why your thoughts always resonates inside my mind...!                                                     > Everything about you is always intresting for me...!                     << I am somewhat nervous Because I haven't said these words to anyone and I won't say to anyone in future...!                                                     > I Love my Parents so much than anything else in this world....!                    << Now You are the only person  whom I love equally with my parents....!                                                             >I Love U <SweetHeart.....! |                  <<<< Give me One chance to Prove my Love ...!";
var speed = 50;
typeWriter();
function typeWriter() {
  if (i < txt1.length) {        
     if(txt1.charAt(i)=='<')
      document.getElementById("text1").innerHTML += '</br>'
    else if(txt1.charAt(i)=='>')
      document.getElementById("text1").innerHTML = ''
    else if(txt1.charAt(i)=='|')
      {
        $(".bg_heart").css("background-image","url('https://i.pinimg.com/originals/51/d8/37/51d8374126446d495348b6032202126f.jpg')");

      }
    else
      document.getElementById("text1").innerHTML += txt1.charAt(i);
    i++;
    setTimeout(typeWriter, speed);
  }
}
  </script>
    
</body>
</html>